// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abbaxljwgiwermxnlega.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiYmF4bGp3Z2l3ZXJteG5sZWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDY2NjYsImV4cCI6MjA2MDMyMjY2Nn0.Q4TNgN1_996A3_5lPaUiqexnkx5MZVeEaGDwTUvns2w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);